### ISSUE TITLE
Various job board suggestion

### ISSUE THREAD

**Issue by CodingCossack** [tramcar/awesome-job-boards#205]
Great repo for tech job boards.
Was hoping you could add an [american culinary job board](https://chefjobsnear.me) to the various category. Thanks in advance.

Hospitality
[Culinary Jobs USA](https://chefjobsnear.me/?utm_source=github&utm_medium=referral&utm_campaign=tramcar-awesome-job-boards) - Sous chef, kitchen manager, cook + more jobs in the US

**Comment by CodingCossack** [comment]
[Culinary Jobs USA](https://chefjobsnear.me/?utm_source=github&utm_medium=referral&utm_campaign=tramcar-awesome-job-boards) -  Sous chef, kitchen manager, cook + more jobs in the US

**Comment by tramcarjobs** [comment]
Hi @CodingCossack , those are not job boards that would fit well into our tech-focused job board list.
